"""Produce appendix-ready artifacts.

Three outputs:

1. results/results_appendix.csv: id + flattened gemini_response from
   results.csv. Whitespace runs (including embedded newlines) collapsed
   to single spaces.

2. results/scoring_appendix.csv: scoring.csv with underscores replaced
   by spaces in style_id and attack_pattern columns so LaTeX p-columns
   can wrap.

3. results/responses_appendix.tex: a LaTeX snippet containing one
   paragraph block per response, with all LaTeX special characters
   escaped. The .tex injection path bypasses csvsimple entirely, which
   was silently dropping rows whose response cells contained quoted
   substrings.

Usage from repo root:
    py scripts\\make_appendix_csvs.py
"""

import csv
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_SRC = REPO_ROOT / "results" / "results.csv"
RESULTS_DST_CSV = REPO_ROOT / "results" / "results_appendix.csv"
RESULTS_DST_TEX = REPO_ROOT / "results" / "responses_appendix.tex"
SCORING_SRC = REPO_ROOT / "results" / "scoring.csv"
SCORING_DST = REPO_ROOT / "results" / "scoring_appendix.csv"
MITIGATION_SRC = REPO_ROOT / "results" / "mitigation.csv"
MITIGATION_DST_TEX = REPO_ROOT / "results" / "mitigation_appendix.tex"

WS_RE = re.compile(r"\s+")

LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "<": r"\textless{}",
    ">": r"\textgreater{}",
}


def latex_escape(text: str) -> str:
    out = []
    for ch in text:
        out.append(LATEX_ESCAPES.get(ch, ch))
    return "".join(out)


def flatten(text: str) -> str:
    return WS_RE.sub(" ", text).strip()


def make_results_appendix():
    if not RESULTS_SRC.exists():
        raise SystemExit(f"missing {RESULTS_SRC}")
    with open(RESULTS_SRC, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    with open(RESULTS_DST_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "gemini_response"])
        writer.writeheader()
        for row in rows:
            writer.writerow({
                "id": row["id"],
                "gemini_response": flatten(row.get("gemini_response", "")),
            })
    print(f"Wrote {RESULTS_DST_CSV}")

    with open(RESULTS_DST_TEX, "w", encoding="utf-8") as f:
        f.write("% Auto-generated by scripts/make_appendix_csvs.py. Do not hand-edit.\n")
        f.write("% Rows for a longtable in report.tex; the longtable preamble\n")
        f.write("% (column spec, \\toprule, \\endhead, \\bottomrule, \\endfoot) lives there.\n")
        n = len(rows)
        for i, row in enumerate(rows):
            rid = latex_escape(row["id"])
            response = latex_escape(flatten(row.get("gemini_response", "")))
            sep = "\\addlinespace" if i < n - 1 else ""
            f.write(f"\\textbf{{{rid}}} & {response} \\\\\n{sep}\n")
    print(f"Wrote {RESULTS_DST_TEX}")


def make_scoring_appendix():
    if not SCORING_SRC.exists():
        raise SystemExit(f"missing {SCORING_SRC}")
    with open(SCORING_SRC, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
        fields = list(rows[0].keys())
    with open(SCORING_DST, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            out = dict(row)
            for col in ("style_id", "attack_pattern"):
                if col in out and out[col]:
                    out[col] = out[col].replace("_", " ")
            writer.writerow(out)
    print(f"Wrote {SCORING_DST}")


def make_mitigation_appendix():
    if not MITIGATION_SRC.exists():
        print(f"skip: {MITIGATION_SRC} does not exist yet")
        return
    with open(MITIGATION_SRC, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    with open(MITIGATION_DST_TEX, "w", encoding="utf-8") as f:
        f.write("% Auto-generated by scripts/make_appendix_csvs.py. Do not hand-edit.\n")
        f.write("% Rows for a longtable in report.tex (mitigation appendix).\n")
        n = len(rows)
        for i, row in enumerate(rows):
            rid = latex_escape(row["id"])
            response = latex_escape(flatten(row.get("gemini_response", "")))
            sep = "\\addlinespace" if i < n - 1 else ""
            f.write(f"\\textbf{{{rid}}} & {response} \\\\\n{sep}\n")
    print(f"Wrote {MITIGATION_DST_TEX}")


def main():
    make_results_appendix()
    make_scoring_appendix()
    make_mitigation_appendix()


if __name__ == "__main__":
    main()
